---
run:
    go: "1.19"
    concurrency: 4
    timeout: 5m
    tests: false
    issues-exit-code: 1    
    skip-dirs:        
        - vendor$
    skip-files:
output:
    sort-results: true
linters:
    # Disable all linters.
    # Default: false
    disable-all: true
    # Enable specific linter
    # https://golangci-lint.run/usage/linters/#enabled-by-default
    enable:
        - asasalint
        - asciicheck
        - bidichk
        - bodyclose
        - containedctx
        - contextcheck
        #    - cyclop
        - decorder
        #    - depguard
        #    - dogsled
        #    - dupl
        - durationcheck
        - errcheck
        - errchkjson
        - errname
        - errorlint
        - execinquery
        # - exhaustive
        #    - exhaustivestruct
        #    - exhaustruct
        - exportloopref
        #    - forcetypeassert
        #    - funlen
        - gci
        #    - gochecknoglobals
        #    - gochecknoinits
        #    - gocognit
        #    - goconst
        - gocritic
        #    - gocyclo
        #    - godot
        #    - godox
        #    - goerr113
        - gofmt
        #    - gofumpt
        - goheader
        #    - goimports
        #    - golint
        #    - gomnd
        #    - gomoddirectives
        - gomodguard
        - goprintffuncname
        - gosec
        - gosimple
        - govet
        - grouper
        - importas
        - ineffassign
        #    - ireturn
        #    - lll
        #    - maintidx
        - makezero
        #    - maligned
        - misspell
        #    - nakedret
        #    - nestif
        - nilerr
        - nilnil
        #    - nlreturn
        #    - noctx
        - nolintlint
        #    - nonamedreturns
        - nosprintfhostport
        - paralleltest
        - prealloc
        #    - predeclared
        - promlinter
        #    - revive
        - rowserrcheck
        - exportloopref
        - sqlclosecheck
        - staticcheck
        - stylecheck
        #    - tagliatelle
        - tenv
        - testpackage
        - thelper
        - tparallel
        - typecheck
        - unconvert
        - unparam
        - unused
        #    - varnamelen
        - wastedassign
        - whitespace
#    - wrapcheck
#    - wsl

linters-settings:
    errcheck:
        check-type-assertions: true
        check-blank: false
    gci:
        sections:
            - standard
            - default            
            - prefix(github.com/555f/go-service-template/internal/api)
            - prefix(github.com/555f/go-service-template/internal/domain)            
            - prefix(github.com/555f/go-service-template/internal/usecase)        
            - prefix(github.com/555f/go-service-template/internal/infrastructure)
            - prefix(github.com/555f/go-service-template/internal/config)
            - prefix(github.com/555f/go-service-template/internal/app)            
            - prefix(github.com/555f/go-service-template/pkg)